import streamlit as st
import yfinance as yf
import pandas as pd
import requests
from datetime import datetime

# Your existing strategy functions (run_930_ce_pe_strategy, run_sma_crossover_option_strategy) here
# (Make sure these functions are defined above this Streamlit app code)

# Example minimal option chain fetcher (you can replace with your own function)
@st.cache_data(ttl=300)
def get_nifty_option_chain_simple():
    url = "https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY"
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://www.nseindia.com/option-chain"
    }
    try:
        session = requests.Session()
        session.headers.update(headers)
        session.get("https://www.nseindia.com", timeout=5)
        response = session.get(url, timeout=5)
        data = response.json()
        records = data['records']['data']

        rows = []
        for rec in records:
            strike = rec.get('strikePrice')
            ce = rec.get('CE', {})
            pe = rec.get('PE', {})
            rows.append({
                'strikePrice': strike,
                'CE_LTP': ce.get('lastPrice'),
                'CE_IV': ce.get('impliedVolatility'),
                'PE_LTP': pe.get('lastPrice'),
                'PE_IV': pe.get('impliedVolatility')
            })
        df = pd.DataFrame(rows)
        return df
    except Exception as e:
        st.error(f"❌ Error fetching option chain: {e}")
        return pd.DataFrame()

@st.cache_data(ttl=3600)
def load_nifty_data():
    df = yf.download("^NSEI", interval="15m", period="10d", progress=False)
    df.reset_index(inplace=True)
    df['datetime'] = pd.to_datetime(df['Datetime'] if 'Datetime' in df.columns else df['datetime'])
    if df['datetime'].dt.tz is None:
        df['datetime'] = df['datetime'].dt.tz_localize('UTC')
    df['datetime'] = df['datetime'].dt.tz_convert('Asia/Kolkata')
    return df

# Streamlit UI starts here
st.set_page_config(page_title="NIFTY Option Strategy Runner", layout="wide")
st.title("📊 NIFTY Option Strategy Backtester")

# Sidebar for strategy selection
strategy = st.sidebar.selectbox(
    "Choose Trading Strategy",
    ("930 CE/PE Strategy", "SMA Crossover Option Strategy")
)

# Load data once
with st.spinner("Loading NIFTY price data..."):
    price_df = load_nifty_data()
with st.spinner("Fetching Option Chain..."):
    option_chain_df = get_nifty_option_chain_simple()

if price_df.empty or option_chain_df.empty:
    st.error("Data loading failed. Check your internet or NSE site availability.")
    st.stop()

# Execute selected strategy
if strategy == "930 CE/PE Strategy":
    st.sidebar.markdown("**Parameters:**")
    target_points = st.sidebar.number_input("Target Points", value=50)
    stop_loss_pct = st.sidebar.number_input("Stop Loss %", value=5)
    
    with st.spinner("Running 930 CE/PE Strategy..."):
        trades_df = run_930_ce_pe_strategy(price_df, option_chain_df, target_points=target_points, sl_pct=stop_loss_pct)
elif strategy == "SMA Crossover Option Strategy":
    st.sidebar.markdown("**Parameters:**")
    target_points = st.sidebar.number_input("Target Points", value=40)
    stop_loss_pct = st.sidebar.number_input("Stop Loss %", value=5)

    with st.spinner("Running SMA Crossover Option Strategy..."):
        trades_df = run_sma_crossover_option_strategy(price_df, option_chain_df, target_points=target_points, sl_pct=stop_loss_pct)

# Show trades on right side
st.subheader(f"Strategy: {strategy}")
if trades_df.empty:
    st.warning("No trades generated by this strategy for selected data.")
else:
    st.dataframe(trades_df)

    # Summary statistics
    total_trades = len(trades_df)
    wins = len(trades_df[trades_df['P&L'] > 0])
    losses = len(trades_df[trades_df['P&L'] <= 0])
    win_rate = (wins / total_trades) * 100 if total_trades > 0 else 0
    total_pnl = trades_df['P&L'].sum()
    avg_pnl = trades_df['P&L'].mean()

    st.markdown(f"""
    **Total Trades:** {total_trades}  
    **Winning Trades:** {wins}  
    **Losing Trades:** {losses}  
    **Win Rate:** {win_rate:.2f}%  
    **Total P&L:** ₹{total_pnl:.2f}  
    **Average P&L per Trade:** ₹{avg_pnl:.2f}
    """)

    # Day-wise performance table
    day_perf = trades_df.groupby('Date').agg(
        Trades=('P&L', 'count'),
        Wins=('P&L', lambda x: (x > 0).sum()),
        Losses=('P&L', lambda x: (x <= 0).sum()),
        Daily_PnL=('P&L', 'sum')
    ).reset_index()

    st.subheader("Day-wise Performance 📅")
    st.dataframe(day_perf)
